* 需要有schema，是为了根据schema读page。格式类似
-------------------------------------------------------------------------
CREATE TABLE LINEITEM ( L_ORDERKEY    INTEGER NOT NULL,
                             L_PARTKEY     INTEGER NOT NULL,
                             L_SUPPKEY     INTEGER NOT NULL,
                             L_LINENUMBER  INTEGER NOT NULL,
                             L_QUANTITY    DECIMAL(15,2) NOT NULL,
                             L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
                             L_DISCOUNT    DECIMAL(15,2) NOT NULL,
                             L_TAX         DECIMAL(15,2) NOT NULL,
                             L_RETURNFLAG  CHAR(1) NOT NULL,
                             L_LINESTATUS  CHAR(1) NOT NULL,
                             L_SHIPDATE    DATE NOT NULL,
                             L_COMMITDATE  DATE NOT NULL,
                             L_RECEIPTDATE DATE NOT NULL,
                             L_SHIPINSTRUCT CHAR(25) NOT NULL,
                             L_SHIPMODE     CHAR(10) NOT NULL,
                             L_COMMENT      VARCHAR(44) NOT NULL);
-------------------------------------------------------------------------

或自定义格式就会比较快，甚至直接根据lineitem写死schema更快。
为了速度，打算直接写死schema。

* to read the table
    . Put it into the appropriate bucket and before this, 
    . check whether the index(equal to page id) is in the memory, if not, fetch it.
    . get the location of the bucket, check whether it's in the memory, if not, fetch it.
    . check if the bucket is full. If not, check whether to double the buckets, or to generate a linked list.
    Note: this means that, first, the bucket should be able to generate a linked list. Second, the redistribution is necessary.
    . Then actual data should be read and saved. The items in the bucket should contain the location(page and index) of the entire corresponding record.
    . Housekeeping value: global depth

* For the pages, 
    . Every bucket contains: its local depth(32 bits = 4 bytes), the number of records(32 bits = 4 bytes, lineitem.tbl has 6001215 records), the `next' pointer(also an integer), the end of data region(integer), then the records, and data region.
    . Every index contains: its lable(integer), and the corresponding page id(bucket, integer). Thus, such a page contains 4k records.
